//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPO_Solutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone_no { get; set; }
        public string Address { get; set; }
        public string City_State { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public string Area_Of_Pain { get; set; }
        public string Health_Insurance_Id { get; set; }
        public string DOB { get; set; }
        public string Status { get; set; }
    }
}
